### ISSUE TITLE
RuntimeError: CreateModel

### ISSUE THREAD

**Issue by ghost** [reuben/ds-qttest#2]
Oi @reuben, eu testei rodar a inferência ./main.py passando o modelo conforme indicado, mas apareceu este erro:

```
TensorFlow: v1.14.0-21-ge77504a
DeepSpeech: v0.6.1-0-g3df20fe
2020-01-22 16:08:30.836573: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-01-22 16:08:31.125058: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] model_pruner failed: Invalid argument: Invalid input graph.
Unable to fetch graph version: Invalid argument: Tensor metadata_version:0, specified in either feed_devices or fetch_devices was not found in the Graph
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./main.py", line 43, in run
    model = Model(model, BEAM_WIDTH)
  File "/novo/luisa/STT/deepspeech/inferencia-venv/lib/python3.6/site-packages/deepspeech/__init__.py", line 42, in __init__
    raise RuntimeError("CreateModel failed with error code {}".format(status))
RuntimeError: CreateModel failed with error code 8195
```

A tela de gravação também abre (com o botão "Record"), no entanto quando tento gravar algo e aperto em "Stop" ele não processa, não acontece nada.

Consegue me ajudar com essa questão?

**Comment by reuben** [comment]
> On 22 Jan 2020, at 20:40, luisamoncorvo <notifications@github.com> wrote:
> 
> Unable to fetch graph version: Invalid argument: Tensor metadata_version:0, specified in either feed_devices or fetch_devices was not found in the Graph

Esse erro parece ser devido a uma incompatibilidade entre as versões do modelo e do cliente. Se você instalou o pacote do deepspeech versão 0.6.1, tem que usar o modelo da mesma versão.

**Comment by ghost** [comment]
Eu estou usando deepspeech 0.6.1 mesmo, e como modelo usei um que o André em passou que vocês treinaram juntos. Este eu não sei confirmar qual versão é...
O André disse que no servidor tem outro modelo mais recente treinado na versão 0.6.1 em ``` /var/corpora/downloader/datasets/20200117181620_minscore90_pontocinco_a_15_segs/deepspeech ```, mas eu só localizei os arquivos do modelo de linguagem .binary e .trie, falta o output_graph.pbmm. Alguma idéia de onde posso encontrar?

**Comment by reuben** [comment]
Então você tem que descobrir qual foi a versão que foi usada pra treinar e exportar esse modelo.

Sobre o modelo mais recente, não sei onde está. O André que tem feito todos os treinos recentemente.
